Update README.md
Real-Dev-Squad/skill-tree-backend pull request #100
Opened 2024-03-06 18:31 UTC by Chethan64

Date: 6 Mar 2024

Developer Name: @Chethan64 

---

## Issue Ticket Number

#94  

## Description

Updating README.md for better setup of the project
- Added steps to create the environment file and run/debug configuration
- Updated few unclear steps

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
NA

</details>

## Test Coverage
NA

## Additional Notes

2024-03-16 08:06 UTC, akhilkh2000 requested changes
Could you also add in the Lombok errors in the "Known issues faced by other developers section". Other than that LGTM

2024-03-16 11:04 UTC, Chethan64 commented
> Could you also add in the Lombok errors in the "Known issues faced by other developers section". Other than that LGTM

It's added as part of IntelliJ setup steps

2024-03-16 11:07 UTC, akhilkh2000 approved these changes

2024-03-19 17:09 UTC, Shaily20 approved these changes

2024-03-24 16:41 UTC, merged