add status filter to get all skill requests api
Real-Dev-Squad/skill-tree-backend pull request #152
Opened 2024-08-26 21:07 UTC by yesyash

Date: 

Developer Name: 

---

## Issue Ticket Number

## Description

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-08-26 21:19 UTC, iamitprakash requested changes

2024-08-26 21:19 UTC, iamitprakash commented on skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java
> +                                    endorsements.forEach(
can we optimize this loop

2024-08-30 19:14 UTC, iamitprakash approved these changes

2024-08-30 19:24 UTC, Achintya-Chatterjee approved these changes

2024-08-30 19:25 UTC, merged